#!/bin/bash
# Assumes $APP_KEY is available
# Similar to init except does not ask api.gigalixir.com for the current slug url.
# This also does not support SSH, observer, etc.
# Current use case for this is when you want to manually specify the slug url instead
# of asking for the current one.
set +ex

REPO=$1
APP=$2
SIGNED_SLUG_URL=$3
CMD="${@:4}"

mkdir -p /kube-env-vars
echo $MY_POD_IP > /kube-env-vars/MY_POD_IP
echo $ERLANG_COOKIE > /kube-env-vars/ERLANG_COOKIE
echo $REPO > /kube-env-vars/REPO
echo $APP > /kube-env-vars/APP

pushd /app
curl -o $APP.tar.gz "$SIGNED_SLUG_URL"
tar zxvf $APP.tar.gz

pushd $(dirname $0)
./run-cmd "$CMD"
