#!/bin/bash
set -euo pipefail

CMD="${@:1}"

# These vars are set by the pod spec and are present EXCEPT when you ssh in manually
# as is the case when you run remote observer or want a remote_console. In those cases
# we pull them from the file system instead. It's a bit of a hack. The init script
# creates those files.
export REPO=$(cat /kube-env-vars/REPO)
export APP=$(cat /kube-env-vars/APP)
export MY_POD_IP=$(cat /kube-env-vars/MY_POD_IP)
export ERLANG_COOKIE=$(cat /kube-env-vars/ERLANG_COOKIE)

# For distillery. So you can put $VARIABLES in your config files.
export REPLACE_OS_VARS=true

# For exrm even though we don't official support exrm.
export RELX_REPLACE_OS_VARS=true
export MY_NODE_NAME=$REPO@$MY_POD_IP
export MY_COOKIE=$ERLANG_COOKIE
export LC_ALL=en_US.UTF-8

# Set up enviroment variables from mounted kubernetes secrets
if [ -d /mnt/secrets ]; then
  for key in $(ls /mnt/secrets); do
      export $key="$(cat /mnt/secrets/$key)"
  done
fi

export LIBCLUSTER_KUBERNETES_SELECTOR="repo=$REPO"
export LIBCLUSTER_KUBERNETES_NODE_BASENAME="$REPO"
exec /app/bin/$APP $CMD

