#!/bin/bash
# assumes $APP_KEY is available
set -exuo pipefail

REPO=$1
APP=$2
VERSION=$3

pushd /app
mkdir -p /app/releases/$VERSION
CURRENT=$(curl https://api.gigalixir.com/api/apps/$REPO/releases/current -u $REPO:$APP_KEY | jq -r '.data.slug_url')
curl -o /app/releases/$VERSION/$APP.tar.gz "$CURRENT"

pushd $(dirname $0)

# support downgrade?
./run-cmd upgrade $VERSION
